import { builtinModules } from "node:module";
import { defineConfig } from "tsup";

const isDev = process.env.npm_lifecycle_event === "dev";

// eslint-disable-next-line import/no-default-export -- Just a config
export default defineConfig({
  clean: true,
  entry: ["src/index.ts"],
  format: ["esm", "cjs"], // Generate both ESM and CommonJS modules
  minify: !isDev, // Minify the output in non-dev mode
  target: "esnext", // Target modern JavaScript
  dts: true, // Generate TypeScript declaration files
  sourcemap: "inline", // Include inline source maps

  // Only mark Node.js built-in modules as external
  external: [...builtinModules],
  bundle: true,
  skipNodeModulesBundle: false,
  noExternal: ["pg", "ora", "chalk", "fs-extra", "inquirer", "yargs", "node-forge"],

  outDir: "dist",
  onSuccess: isDev ? "node dist/index.js" : undefined,
  banner: {
    js: "// Generated by CodeVault LLC - https://github.com/codevault-llc",
  },
});
