import { builtinModules } from "node:module";
import { defineConfig } from "tsup";

const isDev = process.env.npm_lifecycle_event === "dev";

// eslint-disable-next-line import/no-default-export -- Just a config
export default defineConfig({
  clean: true,
  entry: ["src/index.ts"],
  format: !isDev ? ["esm", "cjs"] : ["esm"], // Generate both ESM and CommonJS modules
  minify: !isDev, // Minify the output in non-dev mode
  target: "esnext", // Target modern JavaScript
  sourcemap: !isDev ? "inline" : undefined, // Include inline source maps

  // Only mark Node.js built-in modules as external
  external: !isDev ? [...builtinModules] : undefined,
  bundle: !isDev ? true : undefined,
  skipNodeModulesBundle: !isDev ? false : undefined,
  noExternal: !isDev
    ? ["pg", "ora", "chalk", "fs-extra", "inquirer", "yargs", "node-forge"]
    : undefined,

  outDir: "dist",
  onSuccess: isDev ? "node dist/index.js" : undefined,
  banner: !isDev
    ? {
        js: "// Generated by CodeVault LLC - https://github.com/codevault-llc",
      }
    : undefined,
});
