name: Staging
on:
  push:
    branches:
      - stage
jobs:
  stage:
    name: Stage
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3.1.0
